# from .transformer import make_to_file, make_fr_file
# from ...core.defininitions import DefType, DefProperty, DefSignal, DefValueTyping, HintMap, TypeMap, PropertyUsage

# def test():
#     data = {
#         "classes": [
#             {
#                 "_type": "Class",
#                 "abstract": True,
#                 "extends": "RefCounted",
#                 "global_name": "Resource",
#                 "properties": [
#                     {
#                         "_type": "Property",
#                         "class_name": "",
#                         "default_value": None,
#                         "hint": 0,
#                         "hint_string": "resource_",
#                         "name": "Resource",
#                         "type": 0,
#                         "usage": 64
#                     },
#                 ],
#                 "signals": [
#                     {
#                         "_type": "Signal",
#                         "args": [],
#                         "default_args": [],
#                         "flags": 1,
#                         "id": 0,
#                         "name": "script_changed",
#                         "return": {
#                             "_type": "Value",
#                             "class_name": "",
#                             "hint": 0,
#                             "hint_string": "",
#                             "name": "",
#                             "type": 0,
#                             "usage": 6
#                         }
#                     },
#                 ]
#             }
#         ],
#         "engine": {
#             "build": "official",
#             "hash": "1c8cc9e7e2c9a083cf726e74193d3824fb38cda4",
#             "hex": 263936,
#             "major": 4,
#             "minor": 7,
#             "patch": 0,
#             "status": "beta1",
#             "string": "4.7-beta1 (official)",
#             "timestamp": 0
#         },
#         "hint_map": {
#             "PROPERTY_HINT_NONE":0,
#             "PROPERTY_HINT_RANGE":1,
#             "PROPERTY_HINT_ENUM":2,
#             "PROPERTY_HINT_ENUM_SUGGESTION":3,
#             "PROPERTY_HINT_EXP_EASING":4,
#             "PROPERTY_HINT_LINK":5,
#             "PROPERTY_HINT_FLAGS":6,
#             "PROPERTY_HINT_LAYERS_2D_RENDER":7,
#             "PROPERTY_HINT_LAYERS_2D_PHYSICS":8,
#             "PROPERTY_HINT_LAYERS_2D_NAVIGATION":9,
#             "PROPERTY_HINT_LAYERS_3D_RENDER":10,
#             "PROPERTY_HINT_LAYERS_3D_PHYSICS":11,
#             "PROPERTY_HINT_LAYERS_3D_NAVIGATION":12,
#             "PROPERTY_HINT_FILE":13,
#             "PROPERTY_HINT_DIR":14,
#             "PROPERTY_HINT_GLOBAL_FILE":15,
#             "PROPERTY_HINT_GLOBAL_DIR":16,
#             "PROPERTY_HINT_RESOURCE_TYPE":17,
#             "PROPERTY_HINT_MULTILINE_TEXT":18,
#             "PROPERTY_HINT_EXPRESSION":19,
#             "PROPERTY_HINT_PLACEHOLDER_TEXT":20,
#             "PROPERTY_HINT_COLOR_NO_ALPHA":21,
#             "PROPERTY_HINT_OBJECT_ID":22,
#             "PROPERTY_HINT_TYPE_STRING":23,
#             "PROPERTY_HINT_NODE_PATH_TO_EDITED_NODE":24,
#             "PROPERTY_HINT_OBJECT_TOO_BIG":25,
#             "PROPERTY_HINT_NODE_PATH_VALID_TYPES":26,
#             "PROPERTY_HINT_SAVE_FILE":27,
#             "PROPERTY_HINT_GLOBAL_SAVE_FILE":28,
#             "PROPERTY_HINT_INT_IS_OBJECTID":29,
#             "PROPERTY_HINT_INT_IS_POINTER":30,
#             "PROPERTY_HINT_ARRAY_TYPE":31,
#             "PROPERTY_HINT_LOCALE_ID":32,
#             "PROPERTY_HINT_LOCALIZABLE_STRING":33,
#             "PROPERTY_HINT_NODE_TYPE":34,
#             "PROPERTY_HINT_HIDE_QUATERNION_EDIT":35,
#             "PROPERTY_HINT_PASSWORD":36,
#             "PROPERTY_HINT_LAYERS_AVOIDANCE":37,
#             "PROPERTY_HINT_DICTIONARY_TYPE":38,
#             "PROPERTY_HINT_TOOL_BUTTON":39,
#             "PROPERTY_HINT_ONESHOT":40,
#             "PROPERTY_HINT_GROUP_ENABLE":42,
#             "PROPERTY_HINT_INPUT_NAME":43,
#             "PROPERTY_HINT_FILE_PATH":44,
#             "PROPERTY_HINT_MAX":45,
#         },
#         "type_map": {
#             "Nil":0,
#             "bool":1,
#             "int":2,
#             "float":3,
#             "String":4,
#             "Vector2":5,
#             "Vector2i":6,
#             "Rect2":7,
#             "Rect2i":8,
#             "Vector3":9,
#             "Vector3i":10,
#             "Transform2D":11,
#             "Vector4":12,
#             "Vector4i":13,
#             "Plane":14,
#             "Quaternion":15,
#             "AABB":16,
#             "Basis":17,
#             "Transform3D":18,
#             "Projection":19,
#             "Color":20,
#             "StringName":21,
#             "NodePath":22,
#             "RID":23,
#             "Object":24,
#             "Callable":25,
#             "Signal":26,
#             "Dictionary":27,
#             "Array":28,
#             "PackedByteArray":29,
#             "PackedInt32Array":30,
#             "PackedInt64Array":31,
#             "PackedFloat32Array":32,
#             "PackedFloat64Array":33,
#             "PackedStringArray":34,
#             "PackedVector2Array":35,
#             "PackedVector3Array":36,
#             "PackedColorArray":37,
#             "PackedVector4Array":38
#         },
#         "usage_map":{
#             "PROPERTY_USAGE_ALWAYS_DUPLICATE": 524288,
#             "PROPERTY_USAGE_ARRAY": 262144,
#             "PROPERTY_USAGE_CATEGORY": 128,
#             "PROPERTY_USAGE_CHECKABLE": 16,
#             "PROPERTY_USAGE_CHECKED": 32,
#             "PROPERTY_USAGE_CLASS_IS_BITFIELD": 512,
#             "PROPERTY_USAGE_CLASS_IS_ENUM": 65536,
#             "PROPERTY_USAGE_DEFAULT": 6,
#             "PROPERTY_USAGE_DEFERRED_SET_RESOURCE": 33554432,
#             "PROPERTY_USAGE_EDITOR": 4,
#             "PROPERTY_USAGE_EDITOR_BASIC_SETTING": 134217728,
#             "PROPERTY_USAGE_EDITOR_INSTANTIATE_OBJECT": 67108864,
#             "PROPERTY_USAGE_GROUP": 64,
#             "PROPERTY_USAGE_HIGH_END_GFX": 2097152,
#             "PROPERTY_USAGE_INTERNAL": 8,
#             "PROPERTY_USAGE_KEYING_INCREMENTS": 16777216,
#             "PROPERTY_USAGE_NEVER_DUPLICATE": 1048576,
#             "PROPERTY_USAGE_NIL_IS_VARIANT": 131072,
#             "PROPERTY_USAGE_NODE_PATH_FROM_SCENE_ROOT": 4194304,
#             "PROPERTY_USAGE_NONE": 0,
#             "PROPERTY_USAGE_NO_INSTANCE_STATE": 1024,
#             "PROPERTY_USAGE_READ_ONLY": 268435456,
#             "PROPERTY_USAGE_RESOURCE_NOT_PERSISTENT": 8388608,
#             "PROPERTY_USAGE_RESTART_IF_CHANGED": 2048,
#             "PROPERTY_USAGE_SCRIPT_DEFAULT_VALUE": 32768,
#             "PROPERTY_USAGE_SCRIPT_VARIABLE": 4096,
#             "PROPERTY_USAGE_SECRET": 536870912,
#             "PROPERTY_USAGE_STORAGE": 2,
#             "PROPERTY_USAGE_STORE_IF_NULL": 8192,
#             "PROPERTY_USAGE_SUBGROUP": 256,
#             "PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED": 16384
#         }
#     }
#     res = {
#         "Resource" : DefType(
#             global_name = "Resource",
#             extends = "RefCounted",
#             abstract = True,
#             properties = [
#                 DefProperty(
#                     class_name = "",
#                     default_value = None,
#                     hint = HintMap[0],
#                     hint_string = "resource_",
#                     name = "Resource",
#                     type = TypeMap[0],
#                     usage = PropertyUsage[64],
#                 ),
#             ],
#             signals = [
#                 DefSignal(
#                     args = [],
#                     default_args = [],
#                     flags = 1,
#                     id = 0,
#                     name = "script_changed",
#                     ret = DefValueTyping(
#                         class_name = "",
#                         hint = HintMap[0],
#                         hint_string = "",
#                         name = "",
#                         type = TypeMap[0],
#                         usage = PropertyUsage[6],
#                     )
#                 )
#             ]
#         )
#     }

#     assert to_file(data) == res
