from __future__ import annotations
from ._test_utils import _StructureTest
from ...core.structure import (
    Properties,
    Project,
    ExtResource,
    File,
    Resource,
    NodePath,
    GdSignal,
    Node,
)

class Test_Properties(_StructureTest):...
class Test_Project(_StructureTest):...
class Test_ExtResource(_StructureTest):...
class Test_File(_StructureTest):...
class Test_Resource(_StructureTest):...
class Test_NodePath(_StructureTest):...
class Test_GdSignal(_StructureTest):...
class Test_Node(_StructureTest):...