start : file_resource

// file_import : [COMMENT|property]* cat_resources

file_resource : "[gd_resource" properties "]" ext_resources sub_resources prim_resource
file_tscn : "[gd_scene" properties "]" ext_resources sub_resources node_resources edit_resources
file_settings :  properties cat_resources 

cat_resources : [prim_resource|cat_resource]*
ext_resources : [ext_resource]*
sub_resources : [sub_resource]*
node_resources : [node_resource]*
edit_resources : [edit_resource]*

ext_resource : "[ext_resource" properties "]" properties
sub_resource : "[sub_resource" properties "]" properties
node_resource : "[node" properties "]" properties
edit_resource : "[edit" properties "]" properties

prim_resource : "[resource]" properties
cat_resource : "[" WORD "]" properties //[COMMENT|property]*

properties : [property]*
property : WORD "=" value

value : NULL
      | INF
      | array
      | dictionary
      | nodepath
      | dictionary_explicit
      | array_explicit
      | rid
      | subresource
      | extresource
      | vector2
      | vector3
      | vector4
      | vector2i
      | vector3i
      | vector4i
      | rect2
      | rect2i
      | plane
      | aabb
      | color
      | quaternion
      | basis
      | transform2d
      | transform3d
      | packedbytearray
      | packedint32array
      | packedint64array
      | packedfloat32array
      | packedfloat64array
      | packedstringarray
      | packedvector2array
      | packedvector3array
      | packedvector4array
      | packedcolorarray
      | BOOL
      | NUMBER
      | FLOAT
      | stringname
      | STRING



// Uniform Fixed Len:
packed_2i : NUMBER ("," NUMBER)~1
packed_3i : NUMBER ("," NUMBER)~2
packed_4i : NUMBER ("," NUMBER)~3

packed_2 : FLOAT ("," FLOAT)~1
packed_3 : FLOAT ("," FLOAT)~2
packed_4 : FLOAT ("," FLOAT)~3
packed_6 : FLOAT ("," FLOAT)~5
packed_9 : FLOAT ("," FLOAT)~8
packed_12 : FLOAT ("," FLOAT)~11

// Primitives:

COMMENT : /;.*/

INF_NEG : "-inf"
INF : "inf"
NULL : "null"

BOOL : "true" | "false"

type_anno : "[" type ("," type)* "]"
type : WORD|subresource|extresource|rid

array_explicit : "Array" [type_anno] "(" [array] ")"
array : "[" [value ("," value)*] "]"

dictionary_explicit : "Dictionary" [type_anno] "(" [dictionary] ")"
dictionary : "{" [pair ("," pair)*] "}"
pair : value ":" value

stringname : "&" STRING


// Defered References:

nodepath : "NodePath" [type_anno] "(" [STRING] ")"
subresource : "SubResource" [type_anno] "(" [STRING] ")"
extresource : "ExtResource" [type_anno] "(" [STRING] ")"
rid : "RID" [type_anno] "(" [STRING] ")"

// Vector types:

vector2i : "Vector2i(" [packed_2i] ")"
vector3i : "Vector3i(" [packed_3i] ")"
vector4i : "Vector4i(" [packed_4i] ")"

vector2 : "Vector2(" [packed_2] ")"
vector3 : "Vector3(" [packed_3] ")"
vector4 : "Vector4(" [packed_4] ")"


rect2 : "Rect2(" [packed_4] ")"
rect2i : "Rect2i(" [packed_4i] ")"

plane : "Plane(" [packed_4] ")"


color : "Color(" [packed_4] ")"
aabb : "AABB(" [packed_6] ")"


quaternion : "Quaternion(" [packed_4] ")"


transform2d : "Transform2D(" [packed_6] ")"
transform3d : "Transform3D(" [packed_12] ")"
basis : "Basis(" [packed_9] ")"

// Packed types:

packedbytearray : "PackedByteArray(" [STRING] ")"

packedint32array : "PackedInt32Array(" ( [NUMBER ("," NUMBER)*] )* ")" 
packedint64array : "PackedInt64Array(" ( [NUMBER ("," NUMBER)*] )* ")" 

packedfloat32array : "PackedFloat32Array(" ( [FLOAT ("," FLOAT)*] )* ")" 
packedfloat64array : "PackedFloat64Array(" ( [FLOAT ("," FLOAT)*] )* ")" 

packedstringarray : "PackedStringArray(" ( [STRING ("," STRING)*] )* ")"

packedvector2array : "PackedVector2Array(" [ [packed_2 ("," packed_2)*] ] ")"
packedvector3array : "PackedVector3Array(" [ [packed_3 ("," packed_3)*] ] ")"
packedvector4array : "PackedVector4Array(" [ [packed_4 ("," packed_4)*] ] ")"
packedcolorarray : "PackedColorArray(" [packed_4 ("," packed_4)*] ")"

WORD : (LETTER | "_" | NUMBER | "/" | ".")+

FLOAT : SIGNED_FLOAT | NUMBER

%import common.ESCAPED_STRING   -> STRING
%import common.LETTER    -> LETTER
%import common.SIGNED_INT    -> NUMBER
%import common.SIGNED_FLOAT     
%import common.WS
%ignore WS
%ignore COMMENT