start : file_resource

file_project :  [COMMENT|property]* [resource]* 
file_resource : resource [file_resource_contents|resource]* 
file_resource_contents : "[resource]" resource_body

resource : resource_header resource_body
resource_header : "[" WORD [property]* "]" 
resource_body : [COMMENT|property]*

property : WORD "=" value

value : NULL
      | array
      | dictionary
      | nodepath
      | dictionary_explicit
      | array_explicit
      | subresource
      | extresource
      | vector2
      | vector3
      | vector4
      | vector2i
      | vector3i
      | vector4i
      | rect2
      | aabb
      | color
      | quaternion
      | transform2d
      | transform3d
      | packedbytearray
      | packedint32array
      | packedint64array
      | packedfloat32array
      | packedfloat64array
      | packedstringarray
      | packedvector2array
      | packedvector3array
      | packedvector4array
      | packedcolorarray
      | bool
      | NUMBER
      | FLOAT
      | STRINGNAME
      | STRING


// Primitives:

COMMENT : /;.*/

NULL : "null"

bool : "true" | "false"

type_anno : "[" type ("," type)* "]"
type : WORD|subresource|extresource

array_explicit : "Array" [type_anno] "(" array ")"
array : "[" [value ("," value)*]* "]"

dictionary_explicit : "Dictionary" [type_anno] "(" dictionary ")"
dictionary : "{" [pair ("," pair)*]* "}"
pair : value ":" value

STRINGNAME : "&" STRING

// Defered References:

nodepath : "NodePath" [type_anno] "(" STRING ")"
subresource : "SubResource" [type_anno] "(" STRING ")"
extresource : "ExtResource" [type_anno] "(" STRING ")"

// Vector types:

vector2i : "Vector2i(" [NUMBER ("," NUMBER)~1] ")"
vector3i : "Vector3i(" [NUMBER ("," NUMBER)~2] ")"
vector4i : "Vector4i(" [NUMBER ("," NUMBER)~3] ")"

vector2 : "Vector2(" packed_vector2 ")"
vector3 : "Vector3(" packed_vector3 ")"
vector4 : "Vector4(" packed_vector4 ")"
packed_vector2 : [FLOAT ("," FLOAT)~1]
packed_vector3 : [FLOAT ("," FLOAT)~2]
packed_vector4 : [FLOAT ("," FLOAT)~3]


rect2 : "Rect2(" [NUMBER ("," NUMBER)~3] ")"

color : "Color(" packed_color ")"
packed_color : [FLOAT ("," FLOAT)~3] 

aabb : "AABB(" [FLOAT ("," FLOAT)~5] ")"

quaternion : "Quaternion(" [FLOAT ("," FLOAT)~3] ")"

transform2d : "Transform2D(" [FLOAT ("," FLOAT)~5] ")"
transform3d : "Transform3D(" [FLOAT ("," FLOAT)~11] ")"

// Packed types:

packedbytearray : "PackedByteArray(" STRING* ")" 

packedint32array : "PackedInt32Array(" ( [NUMBER ("," NUMBER)*] )* ")" 
packedint64array : "PackedInt64Array(" ( [NUMBER ("," NUMBER)*] )* ")" 

packedfloat32array : "PackedFloat32Array(" ( [FLOAT ("," FLOAT)*] )* ")" 
packedfloat64array : "PackedFloat64Array(" ( [FLOAT ("," FLOAT)*] )* ")" 

packedstringarray : "PackedStringArray(" ( [STRING ("," STRING)*] )* ")"

packedvector2array : "PackedVector2Array(" ( [packed_vector2 ("," packed_vector2)*]* )* ")"
packedvector3array : "PackedVector3Array(" ( [packed_vector3 ("," packed_vector3)*]* )* ")"
packedvector4array : "PackedVector4Array(" ( [packed_vector4 ("," packed_vector4)*]* )* ")"
packedcolorarray : "PackedColorArray(" ( [packed_color ("," packed_color)*] )* ")"

WORD : (LETTER | "_" | NUMBER | "/")+

FLOAT : SIGNED_FLOAT | NUMBER

%import common.ESCAPED_STRING   -> STRING
%import common.LETTER    -> LETTER
%import common.SIGNED_INT    -> NUMBER
%import common.SIGNED_FLOAT     
%import common.WS
%ignore WS
%ignore COMMENT