// something

// value: dict 
//      | list
//      | STRING
//      | NUMBER
//      | "true" | "false" | "null"

// list : "[" [value ("," value)*] "]"

// dict : "{" [pair ("," pair)*] "}"
// pair : STRING ":" value

start : file

file : file_project
     | file_resource

file_project :  [COMMENT|property]* [sub_resource]* 
file_resource : sub_resource [sub_resource]*

// resource_header : "[" WORD [property*] "]" [COMMENT|property]*
sub_resource : "[" WORD [property]* "]" [COMMENT|property]*

property : WORD "=" value

value : NULL
      | array
      | dictionary
      | nodepath
      | dictionary_explicit
      | array_explicit
      | subresource
      | extresource
      | vector2
      | vector3
      | vector4
      | vector2i
      | vector3i
      | vector4i
      | aabb
      | color
      | quaternion
      | transform3d
      | packedbytearray
      | packedint32array
      | packedint64array
      | packedfloat32array
      | packedfloat64array
      | packedstringarray
      | packedvector2array
      | packedvector3array
      | packedvector4array
      | packedcolorarray
      | bool
      | FLOAT
      | NUMBER
      | STRINGNAME
      | STRING


// Primitives:

COMMENT : /;.*/

NULL : "null"

bool : "true" | "false"

type : "[" WORD ("," WORD)* "]"

array_explicit : "Array" type* "(" array ")"
array : "[" [value ("," value)*]* "]"

dictionary_explicit : "Dictionary" type* "(" dictionary ")"
dictionary : "{" [pair ("," pair)*]* "}"
pair : value ":" value

STRINGNAME : "&" STRING

// Defered References:

nodepath : "NodePath" type* "(" STRING ")"
subresource : "SubResource" type* "(" STRING ")"
extresource : "ExtResource" type* "(" STRING ")"

// Vector types:

vector2i : "Vector2i(" [NUMBER ("," NUMBER)~1] ")"
vector3i : "Vector3i(" [NUMBER ("," NUMBER)~2] ")"
vector4i : "Vector4i(" [NUMBER ("," NUMBER)~3] ")"

vector2 : "Vector2(" packed_vector2 ")"
vector3 : "Vector3(" packed_vector3 ")"
vector4 : "Vector4(" packed_vector4 ")"
packed_vector2 : [NUMBER ("," NUMBER)~1]
packed_vector3 : [NUMBER ("," NUMBER)~2]
packed_vector4 : [NUMBER ("," NUMBER)~3]

color : "Color(" packed_color ")"
packed_color : [FLOAT ("," FLOAT)~3] 

aabb : "AABB(" [FLOAT ("," FLOAT)~5] ")"

quaternion : "Quaternion(" [FLOAT ("," FLOAT)~3] ")"

transform3d : "Transform3D(" [FLOAT ("," FLOAT)~11] ")"

// Packed types:

packedbytearray : "PackedByteArray(" STRING* ")" 

packedint32array : "PackedInt32Array(" ( [NUMBER ("," NUMBER)*] )* ")" 
packedint64array : "PackedInt64Array(" ( [NUMBER ("," NUMBER)*] )* ")" 

packedfloat32array : "PackedFloat32Array(" ( [FLOAT ("," FLOAT)*] )* ")" 
packedfloat64array : "PackedFloat64Array(" ( [FLOAT ("," FLOAT)*] )* ")" 

packedstringarray : "PackedStringArray(" ( [STRING ("," STRING)*] )* ")"

packedvector2array : "PackedVector2Array(" ( [packed_vector2 ("," packed_vector2)*]* )* ")"
packedvector3array : "PackedVector3Array(" ( [packed_vector3 ("," packed_vector3)*]* )* ")"
packedvector4array : "PackedVector4Array(" ( [packed_vector4 ("," packed_vector4)*]* )* ")"
packedcolorarray : "PackedColorArray(" ( [packed_color ("," packed_color)*] )* ")"

WORD : (LETTER | "_" | NUMBER | "/")+

FLOAT : SIGNED_FLOAT | NUMBER

%import common.ESCAPED_STRING   -> STRING
%import common.LETTER    -> LETTER
%import common.SIGNED_NUMBER    -> NUMBER
%import common.SIGNED_FLOAT     
%import common.WS
%ignore WS
%ignore COMMENT